server:
  port: 8081

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
