global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
    metrics_path: "/metrics"

  # Mikroservisleri ekleyeceğiz
  - job_name: "order-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["order-service:8080"]

  - job_name: "inventory-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["inventory-service:8082"]

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:8081"]
